events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;

        location /api/events {
            proxy_pass http://127.0.0.1:8257;
        }

        location /api/other {
            proxy_pass http://127.0.0.1:8258;
        }
    }
}