# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tevents.v1\"\x1a\n\x0c\x45ventRequest\x12\n\n\x02id\x18\x01 \x01(\t\"O\n\rEventResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06serial\x18\x04 \x01(\t\"\x1f\n\x10SubscribeRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t\"t\n\x0b\x45ventUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nevent_type\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x0e\n\x06serial\x18\x06 \x01(\t2\x98\x01\n\rEventsService\x12=\n\x08GetEvent\x12\x17.events.v1.EventRequest\x1a\x18.events.v1.EventResponse\x12H\n\x0fSubscribeEvents\x12\x1b.events.v1.SubscribeRequest\x1a\x16.events.v1.EventUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTREQUEST']._serialized_start=28
  _globals['_EVENTREQUEST']._serialized_end=54
  _globals['_EVENTRESPONSE']._serialized_start=56
  _globals['_EVENTRESPONSE']._serialized_end=135
  _globals['_SUBSCRIBEREQUEST']._serialized_start=137
  _globals['_SUBSCRIBEREQUEST']._serialized_end=168
  _globals['_EVENTUPDATE']._serialized_start=170
  _globals['_EVENTUPDATE']._serialized_end=286
  _globals['_EVENTSSERVICE']._serialized_start=289
  _globals['_EVENTSSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
